const defaultFiles={html:`<!DOCTYPE html>\n<html lang="es">\n<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>Mi página</title>\n</head>\n<body>\n  <h1>Hola, LabCode Mobile 🚀</h1>\n  <p>Escribe tu código y presiona Ejecutar.</p>\n</body>\n</html>`,css:`body {\n  font-family: Arial, sans-serif;\n  margin: 0;\n  padding: 40px;\n  background-color: #101827;\n  color: #ffffff;\n}\n\nh1 {\n  color: #38bdf8;\n}`,js:`console.log("LabCode Mobile funcionando");`,readme:`# LabCode Mobile\n\nEditor móvil inspirado en VS Code.\n\n- HTML\n- CSS\n- JavaScript\n- Preview\n- Guardado local`,privacy:`Política de privacidad\n\nLos proyectos se almacenan localmente en este dispositivo.`};
let files={...defaultFiles};let current='html';
const $=id=>document.getElementById(id);const editor=$('editor');const lineNumbers=$('lineNumbers');
try{const saved=localStorage.getItem('labcode-mobile-project');if(saved) files={...defaultFiles,...JSON.parse(saved)}}catch(e){}
function save(){files[current]=editor.value;localStorage.setItem('labcode-mobile-project',JSON.stringify(files));showToast('Proyecto guardado en este dispositivo');}
function updateLines(){const count=Math.max(1,editor.value.split('\n').length);lineNumbers.innerHTML=Array.from({length:count},(_,i)=>`<div>${i+1}</div>`).join('');}
function updateCursor(){const before=editor.value.slice(0,editor.selectionStart);const lines=before.split('\n');$('cursorPos').textContent=`Ln ${lines.length}, Col ${lines[lines.length-1].length+1}`}
function loadFile(file){if(!files[file])return;files[current]=editor.value;current=file;editor.value=files[file];$('breadcrumbFile').textContent=file==='html'?'index.html':file==='css'?'style.css':file==='js'?'script.js':file==='readme'?'README.md':'privacy-policy';document.querySelectorAll('[data-file]').forEach(x=>x.classList.toggle('active',x.dataset.file===file));$('editor').focus();updateLines();updateCursor();$('editor').setAttribute('data-lang',file);}
function runCode(){files[current]=editor.value;saveSilent();const html=files.html||'';const css=files.css||'';const js=files.js||'';const source=`${html.replace('</head>',`<style>${css}</style></head>`).replace('</body>',`<script>${js.replaceAll('</script>','<\\/script>')}</script></body>`)}`;$('preview').srcdoc=source;showToast('Código ejecutado');}
function saveSilent(){localStorage.setItem('labcode-mobile-project',JSON.stringify(files))}
function showPreview(){runCode();$('editorWrap').classList.add('hidden');$('previewWrap').classList.remove('hidden');$('previewMode').classList.add('active');$('editorMode').classList.remove('active')}
function showEditor(){$('previewWrap').classList.add('hidden');$('editorWrap').classList.remove('hidden');$('editorMode').classList.add('active');$('previewMode').classList.remove('active')}
function showToast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),1700)}
function openModal(title,html){$('modalTitle').textContent=title;$('modalContent').innerHTML=html;$('modalBackdrop').classList.remove('hidden')}
function privacy(){openModal('⚖ Privacidad',`<div class="modal-body"><h3>LabCode Mobile</h3><p><b>Política de privacidad</b></p><ul><li>No recopilamos datos personales.</li><li>Los proyectos se guardan localmente en tu dispositivo.</li><li>No compartimos tu código con terceros.</li><li>La vista previa se ejecuta dentro de esta aplicación web.</li></ul><p>Última actualización: 29 de septiembre de 2026.</p></div>`)}
$('editor').addEventListener('input',()=>{files[current]=editor.value;updateLines();updateCursor();saveSilent()});['keyup','click','select'].forEach(e=>editor.addEventListener(e,updateCursor));editor.addEventListener('scroll',()=>{lineNumbers.scrollTop=editor.scrollTop});
document.querySelectorAll('.file-item,.tab').forEach(el=>el.addEventListener('click',()=>{loadFile(el.dataset.file);if(window.innerWidth<=700)$('sidebar').classList.remove('open')}));
document.querySelectorAll('.activity').forEach(el=>el.addEventListener('click',()=>{if(el.dataset.panel==='explorer'){ $('sidebar').classList.toggle('open');return}showToast(el.dataset.panel==='search'?'Buscar: próximamente':'Panel disponible próximamente')}));
$('menuBtn').onclick=()=>$('sidebar').classList.toggle('open');$('closeSidebar').onclick=()=>$('sidebar').classList.remove('open');$('runBtn').onclick=runCode;$('saveBtn').onclick=save;$('editorMode').onclick=showEditor;$('previewMode').onclick=showPreview;$('refreshPreview').onclick=runCode;$('openPreview').onclick=()=>{const w=window.open();if(w){w.document.write($('preview').srcdoc);w.document.close()}};$('privacyBtn').onclick=privacy;$('privacyMenu').onclick=()=>{ $('moreMenu').classList.add('hidden');privacy()};$('modalClose').onclick=()=>$('modalBackdrop').classList.add('hidden');$('modalBackdrop').onclick=e=>{if(e.target===$('modalBackdrop'))$('modalBackdrop').classList.add('hidden')};$('moreBtn').onclick=()=>$('moreMenu').classList.toggle('hidden');document.addEventListener('click',e=>{if(!e.target.closest('#moreBtn')&&!e.target.closest('#moreMenu'))$('moreMenu').classList.add('hidden')});$('clearBtn').onclick=()=>{if(confirm('¿Borrar el proyecto guardado y volver al ejemplo?')){files={...defaultFiles};current='html';editor.value=files.html;saveSilent();loadFile('html');showToast('Proyecto restaurado')}};$('settingsBtn').onclick=()=>showToast('Configuración: próximamente');$('newFileBtn').onclick=()=>{const name=prompt('Nombre del archivo, por ejemplo app.js');if(!name)return;showToast(`Archivo ${name} preparado para la próxima versión`)};
editor.addEventListener('keydown',e=>{if(e.key==='Tab'){e.preventDefault();const start=editor.selectionStart,end=editor.selectionEnd;editor.value=editor.value.slice(0,start)+'  '+editor.value.slice(end);editor.selectionStart=editor.selectionEnd=start+2;files[current]=editor.value;updateLines();saveSilent()}});
loadFile('html');runCode();
